name: Folder Sync

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install psycopg2

    - name: Run FolderSync
      run: |
        python -c "from your_module import FolderSync; folder_sync = FolderSync('sql-training-db.csuzplcoqc0i.ap-south-1.rds.amazonaws.com', 'Mehak', 'postgres', 'Pstraining123$', r'C:\Users\hp\Desktop\Source', r'C:\Users\hp\Desktop\Target'); folder_sync.run()"
